FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

# важно: указываем app.api.main, т.к. main.py лежит в app/api/main.py
CMD ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
