"""add manager and working_hours to branches

Revision ID: 321110387098
Revises: 0dc67413e59c
Create Date: 2026-04-16 22:39:39.262547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '321110387098'
down_revision: Union[str, Sequence[str], None] = '0dc67413e59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.add_column('branches', sa.Column('manager_name', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('manager_position', sa.String(length=255), nullable=True))
    op.add_column('branches', sa.Column('working_hours', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'working_hours')
    op.drop_column('branches', 'manager_position')
    op.drop_column('branches', 'manager_name')
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('policy', 'schedule', 'template', 'contract', 'receipt', 'other', name='documentcategory'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('documents_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    # ### end Alembic commands ###
